models_over_bins:
  reference_frames:
    workcell::bin1::link:
      models:
        part1:
          xyz_start: [-0.2, 0., 0.725]
          xyz_end: [0.2, 0., 0.725]
          rpy: [0, 0, '-pi/2']
          num_models_x: 4
          num_models_y: 1

    workcell::bin4::link:
      models:
        part1:
          xyz_start: [-0.2, 0., 0.725]
          xyz_end: [0.2, 0., 0.725]
          rpy: [0, 0, '-pi/2']
          num_models_x: 4
          num_models_y: 1

    workcell::bin6::link:
      models:
        part4:
          xyz_start: [-0.2, -0.2, 0.725]
          xyz_end: [0.2, 0.2, 0.725]
          rpy: [0, 0, 'pi/2']
          num_models_x: 4
          num_models_y: 5

# This is the format for spawning models in a particular
# reference frame, as this can't be done in SDF.

# models_to_spawn:
#   reference_frames:
#     workcell::bin8::link:
#       models:
#         part_0:
#           type: part2
#           pose:
#             xyz: [0.1, 0.1, 0.725]
#             rpy: [0, 0, 0]
