# In this scenario:
# - the conveyor belt is not used
# - there is one order consisting of two types of parts, found in the bins

options:
  insert_models_over_bins: true
  fill_demo_tray: false
  model_type_aliases:
    order_part1: piston_rod_part
    order_part2: gear_part

orders:
  order_0:
    announcement_time: 0.0
    parts:
      part_0:
        type: order_part1
        pose:
          xyz: [0.1, -0.2, 0]
          rpy: [0, 0, 0]
      part_1:
        type: order_part1
        pose:
          xyz: [-0.1, -0.2, 0]
          rpy: [0, 0, 0]
      part_2:
        type: order_part2
        pose:
          xyz: [0.15, 0.15, 0]
          rpy: [0, 0, 0]
      part_3:
        type: order_part2
        pose:
          xyz: [-0.15, 0.15, 0]
          rpy: [0, 0, 0]
      part_4:
        type: order_part2
        pose:
          xyz: [0.0, 0.15, 0]
          rpy: [0, 0, 0]

models_over_bins:
  bin1:
    models:
      piston_rod_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.5, 0.5, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 3
        num_models_y: 4

  bin2:
    models:
      pulley_part:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.45, 0.45, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 2

  bin3:
    models:
      gear_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.5, 0.5, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 5
        num_models_y: 5

  bin4:
    models:
      gasket_part:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.45, 0.45, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 2

  bin8:
    models:
      pulley_part:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.45, 0.45, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 2

  bin7:
    models:
      piston_rod_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.5, 0.5, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 3
        num_models_y: 4

  bin6:
    models:
       gear_part:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.5, 0.5, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 5
        num_models_y: 5

  bin5:
    models:
       part4:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.5, 0.5, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 4
        num_models_y: 5
