options:
  insert_models_over_bins: true
  fill_demo_tray: false
  model_type_aliases:
    order_part1: part3
    order_part2: part4
    order_part3: part1
    order_part4: part2


belt_parts:
  1.0:
    type: order_part1
    pose:
      xyz: [0.0, 0.0, 0.1]
      rpy: [0, 0, 'pi/2']
  2.0:
    type: order_part3
    pose:
      xyz: [0.0, 0.0, 0.1]
      rpy: [0, 0, 'pi/2']

orders:
  order_0:
    announcement_time: 0.0
    parts:
      part_0:
        type: order_part1
        pose:
          xyz: [0.15, 0.15, 0]
          rpy: [0, 0, 0.5]
      part_1:
        type: order_part2
        pose:
          xyz: [-0.15, -0.15, 0]
          rpy: [0, 0, -0.5]
  order_1:
    announcement_time: 20.0
    parts:
      part_0:
        type: order_part3
        pose:
          xyz: [0.1, 0.1, 0]
          rpy: [0, 0, 0.5]
      part_1:
        type: order_part4
        pose:
          xyz: [-0.1, -0.1, 0]
          rpy: [0, 0, 0.0]

models_over_bins:
  bin7:
    models:
       order_part2:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.5, 0.5, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 3
        num_models_y: 3

  bin8:
    models:
       order_part4:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.5, 0.5, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 4
        num_models_y: 5
